---
title: "SpeedTest Results"
output: html_notebook
---

This notebook gets the latest results for the SpeedTest that have been run and plots them.

```{r setup, echo = FALSE, warning = FALSE}

library(tidyverse)
library(lubridate)
library(googlesheets4)

# Get the ID for the Google Sheet where the results are stored. The technique below expects this
# ID to be recorded in .Renviron more another environment file in a variable called "SPEEDTEST_GSHEET."
# Alternatively, you can just hardcode the Google Sheets ID in a variable:
# gsheet <- "[sheet ID]"
gsheet <- Sys.getenv("SPEEDTEST_GSHEET")

# Set the timezone for displaying the results
timezone <- "America/New_York"

```

## Get the Data

The data gets read from the Google Sheets file specified in the setup. There is one dataset (sheet) for the download tests and one dataset (sheet) for the upload tests.

```{r get_data, echo = FALSE, warning = FALSE, message = FALSE}

download_data <- sheets_read(gsheet, "Download Data")
upload_data <- sheets_read(gsheet, "Upload Data")

```

## Visualize the Data

```{r visualize, echo=FALSE, warning=FALSE, message=FALSE}
# Set up theme
theme_plot <- theme_minimal() +
  theme(plot.title.position = "plot",
        plot.subtitle = element_text(face = "italic", colour = "gray40"),
        panel.grid.major.x = element_line(),
        panel.grid.minor.x = element_blank(),
        axis.title.x = element_text(colour = "gray40", margin = margin(5, 0, 0, 0, "pt")),
        axis.title.y = element_text(colour = "gray40", margin = margin(0, 5, 0, 0, "pt")),
        axis.text.y = element_text(colour = "gray30", face = "bold", size = 10))

# Function to build a plot summary of either a download or an upload test
get_plot <- function(test_data){
  
  # Determine if this is an upload dataset or download dataset so the plot can be labeled appropriately
  if(test_data$test[[1]] == "download"){
    label_title <- "Download"
  } else {
    label_title <- "Upload"
  }
  
  # Update the timezone to display in the timezome specified in the setup
  test_data <- test_data %>% 
    mutate(test_time = with_tz(test_time, timezone))
  
  # Get summary statistics for each round of tests
  data_viz_df <- test_data %>% 
    group_by(test_time) %>% 
    summarize(bw_median = median(bw),
              bw_mean = mean(bw),  # Note used, but adding for giggles if we wanted to chat mean vs median
              bw_first_quartile = quantile(bw, .25),
              bw_third_quartile = quantile(bw, .75))
  
  # Get the overall median of all tests for a horizonal line
  bw_median_overall <- median(test_data$bw)
  
  # Build the plot
  gg <- ggplot(data_viz_df, 
               aes(x = test_time, y = bw_median, 
                   ymin = bw_first_quartile, ymax = bw_third_quartile)) +
    geom_ribbon(fill = "gray80", alpha = 0.3) +
    # Overall Median
    geom_hline(mapping = aes(yintercept = bw_median_overall),
               linetype = "dashed", colour = "gray60", size = 0.7) +
    # Median by Hour
    geom_line(color = "#BF5700", size = 1) +    # Hook 'em Horns!
    scale_x_datetime(date_breaks = "1 days", date_labels = "%m/%d") +
    labs(title = paste(label_title, "Speed (Mbps) by Hour: The Overall Median Was", 
                       round(bw_median_overall,1), "Mbps"),
         subtitle = "The Gray Band Represents the 1st and 3rd Quartiles of the Hourly Tests",
         x = "Test Date / Time",
         y = paste("Median", label_title, "Speed (Mbps)")) +
    theme_plot
  
  gg
}

gg_download <- get_plot(download_data)
gg_upload <- get_plot(upload_data)

gg_download
gg_upload


```